apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfqia3194-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfqia3194-tenant-component
    app.kubernetes.io/part-of: loadfqia3194-tenant-app
  name: loadfqia3194-tenant-component
  namespace: loadfqia3194-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadfqia3194-tenant-component
    weight: null
status: {}
