apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfqia3194-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfqia3194-tenant-component
    app.kubernetes.io/part-of: loadfqia3194-tenant-app
  name: loadfqia3194-tenant-component
  namespace: loadfqia3194-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadfqia3194-tenant-component
status:
  loadBalancer: {}
